---
title: "Deber_1Rmarkdown"
author: "Anderson Yumbo"
date: "26/2/2022"
output:
 html_document:
    fig_height: 6
    fight_width: 8
    theme: journal
    highlight: zenburn
    toc: yes
    toc_depht: 4
    toc_float:
      collapsed: no
      smooth_scroll: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Deber 1 en Rmarkdown
### Ejercicio 1

```{r Ejercicio 1}
# Ejercicio 1:

ciudad <- "Archidona"

print(ciudad)

```
### Ejercicio 2:


```{r Ejerc2}

# Ejercicio2:

pais_andes <- c("Venezuela", "Colombia", "Ecuador", "Peru", "Bolivia", "Argentina", "Chile")

print(pais_andes)

```
### Ejercicio 3:

```{r Ejerc3}

### Ejercicio3:

Datos_estudiantes = data.frame(num_Estudiantes = paste0("N.Estudiantes", 1:12), Nombre = c("Mariana", "Melanie", "Dominic", "Romel", "Jorge", "Klever", "Ronal", "Matias", "Jose", "Caroline", "Jose", "Isidro"), Apellido = c("Silva", "Reyes", "Pazmiño", "Alvarado", "Vargas", "Palacios", "Shiguango", "Torres", "Serrano", "Romero", "Bacquet", "Gonzales"), NOta = sample(1:10, 12, replace = TRUE), lista_estudiantes =sample(1:12, 12, replace = TRUE) )

Datos_estudiantes
```
### Ejecicio 4:

* Ejecicio 4.1:

```{r Ejerc41}

# Ejercicio 4.1:

# dataset "DNase"
?DNase

print(head(DNase, 4))

concentration_1 = subset(DNase, conc >= 0.1 & conc <= 0.2)

print(concentration_1)

```
```{r Ejerc42}

# Ejercicio 4.2:

# dataset "DNase"

?DNase

concentration_2 = subset(DNase, Run != 5 & conc > 0.2 & density <= 1.0)

print(concentration_2)

```